config/routes.rb
Rails.application.routes.draw do
  resources :foods
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/food.rb
class Food < ApplicationRecord
    enum sales_status_ : {
        sold_out: 0,
        now_on_sale: 1
    }
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/foods/edit.html.erb
<h1>edit</h1>

app/views/foods/index.html.erb
<h1>index<h1>

app/views/foods/new.html.erb
<div>
<h1>メニュー追加</h1>
    <%= form_with model: @food do |f| %>
        <p><%= f.text_field :name , placeholder:"品名" %></p>
        <p><%= f.number_field :value, placeholder:"金額" %></p>
        <p><%= f.number_field :quantitiy, placeholder:"在庫数" %></p>
        <p><%= f.number_field :statement, placeholder:"状況" %></p>
        <p><%= f.submit "追加" %></p>
    <% end %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderRevolution</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to "メニュー設定/一覧", new_food_path %>

    </header>
    <%= yield %>
  </body>
</html>